---
name: Moose-Policy
version: 0.04
author:
  - 'Stevan Little E<lt>stevan@iinteractive.comE<gt>'
abstract: Moose-mounted police
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::Exception: 0.21
  Test::More: 0.62
requires:
  Moose: 0.84
configure_requires:
  Module::Build: 0.35
provides:
  Moose::Policy:
    file: lib/Moose/Policy.pm
    version: 0.04
  Moose::Policy::FollowPBP:
    file: lib/Moose/Policy/FollowPBP.pm
  Moose::Policy::FollowPBP::Attribute:
    file: lib/Moose/Policy/FollowPBP.pm
  Moose::Policy::JavaAccessors:
    file: lib/Moose/Policy/JavaAccessors.pm
  Moose::Policy::JavaAccessors::Attribute:
    file: lib/Moose/Policy/JavaAccessors.pm
  Moose::Policy::SingleInheritence:
    file: lib/Moose/Policy/SingleInheritence.pm
  Moose::Policy::SingleInheritence::MetaClass:
    file: lib/Moose/Policy/SingleInheritence.pm
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
