---
name: Moose-Policy
version: 0.03
author:
  - 'Stevan Little E<lt>stevan@iinteractive.comE<gt>'
abstract: Moose-mounted police
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Moose: 0.20
build_requires:
  Test::Exception: 0.21
  Test::More: 0.62
provides:
  Moose::Policy:
    file: lib/Moose/Policy.pm
    version: 0.03
  Moose::Policy::FollowPBP:
    file: lib/Moose/Policy/FollowPBP.pm
  Moose::Policy::FollowPBP::Attribute:
    file: lib/Moose/Policy/FollowPBP.pm
  Moose::Policy::JavaAccessors:
    file: lib/Moose/Policy/JavaAccessors.pm
  Moose::Policy::JavaAccessors::Attribute:
    file: lib/Moose/Policy/JavaAccessors.pm
  Moose::Policy::SingleInheritence:
    file: lib/Moose/Policy/SingleInheritence.pm
  Moose::Policy::SingleInheritence::MetaClass:
    file: lib/Moose/Policy/SingleInheritence.pm
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
