---
name: Moose-Policy
version: 0.01
author:
  - 'Stevan Little E<lt>stevan@iinteractive.comE<gt>'
abstract: moose-mounted police
license: perl
requires:
  Carp: 0
  Moose: 0.11
  Scalar::Util: 1.18
build_requires:
  Test::Exception: 0.21
  Test::More: 0.62
provides:
  Moose::Policy:
    file: lib/Moose/Policy.pm
    version: 0.01
  Moose::Policy::FollowPBP:
    file: lib/Moose/Policy/FollowPBP.pm
  Moose::Policy::FollowPBP::Attribute:
    file: lib/Moose/Policy/FollowPBP.pm
  Moose::Policy::JavaAccessors:
    file: lib/Moose/Policy/JavaAccessors.pm
  Moose::Policy::JavaAccessors::Attribute:
    file: lib/Moose/Policy/JavaAccessors.pm
  Moose::Policy::SingleInheritence:
    file: lib/Moose/Policy/SingleInheritence.pm
  Moose::Policy::SingleInheritence::MetaClass:
    file: lib/Moose/Policy/SingleInheritence.pm
generated_by: Module::Build version 0.2611
